wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.11
    start_time: 1648827272
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      4: 3.9.11
      5: 0.12.11
      8:
      - 2
      - 5
