python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.0001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.0005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.001 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.005 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.01 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type none --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 3 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 4 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 5 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 6 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 10 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 28 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 56 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
python3 run_grand_ex.py --depth 112 --discritize_type norm --step_size 0.05 --dataset Cora --run_time 2
