python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 3 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-06 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 1e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 4.0 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.0 --truncate_norm
python3 run_grand_ex.py --dataset Cora --depth 4 --step_size 5e-05 --discritize_type frobenius_norm --norm_exp 3.5 --run_time A10_FPT_Cloud_second --truncate_coeff 2.5 --truncate_norm
